kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node
    commands:
      - yarn install --frozen-lockfile
    when:
      branch:
        include:
          - master
          - develop
          - 'feature/*'
          - 'hotfix/*'
        exlude:
          - 'renovate/*'

  - name: build
    image: node
    commands:
      - yarn build
    when:
      branch:
        include:
          - master
          - develop
          - 'feature/*'
          - 'hotfix/*'
        exlude:
          - 'renovate/*'
    environment:
      DATO_API_TOKEN:
        from_secret: DATO_API_TOKEN
      GATSBY_SENTRY_DSN:
        from_secret: GATSBY_SENTRY_DSN
    depends_on:
      - install

  - name: lighthouse
    image: stiforr/node-chrome:latest
    commands:
      - lhci autorun
    when:
      branch:
        include:
          - master
          - develop
          - 'feature/*'
          - 'hotfix/*'
        exlude:
          - 'renovate/*'
    environment:
      LHCI_TOKEN:
        from_secret: LHCI_TOKEN
      LHCI_GITHUB_APP_TOKEN:
        from_secret: LHCI_GITHUB_APP_TOKEN
    depends_on:
      - install
      - build

  # - name: tests
  #   image: cypress/included:6.5.0
  #   commands:
  #     - cypress install
  #     - yarn test:e2e:ci
  #   environment:
  #     DATO_API_TOKEN:
  #       from_secret: DATO_API_TOKEN
  #     GATSBY_SENTRY_DSN:
  #       from_secret: GATSBY_SENTRY_DSN
  #   depends_on:
  #     - install

  - name: deploy
    image: node
    commands:
      - yarn global add firebase-tools firebase-ci
      - firebase-ci deploy
    environment:
      FIREBASE_TOKEN:
        from_secret: FIREBASE_TOKEN
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
          - tag
    depends_on:
      - build

  # - name: deploy_preview
  #   image: node
  #   commands:
  #     - yarn global add firebase-tools firebase-ci
  #     - firebase use default
  #     - firebase hosting:channel:deploy "${DRONE_BRANCH}"
  #   environment:
  #     FIREBASE_TOKEN:
  #       from_secret: FIREBASE_TOKEN
  #   when:
  #     branch:
  #       - 'feature/*'
  #       - develop
  #     event:
  #       exclude:
  #         - pull_request
  #         - tag
  #   depends_on:
  #     - build

  - name: semantic-release
    image: node
    commands:
      - yarn semantic-release
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
          - tag
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    depends_on:
      - build
      - deploy
