kind: pipeline
type: docker
name: default

steps:
  - name: 'build and install'
    image: cypress/included:6.5.0
    volumes:
      - name: cypress-cache
        path: /root/.cache/Cypress
    commands:
      - yarn install --frozen-lockfile
      - yarn build
    environment:
      DATO_API_TOKEN:
        from_secret: DATO_API_TOKEN
      GATSBY_SENTRY_DSN:
        from_secret: GATSBY_SENTRY_DSN

  - name: tests
    image: cypress/included:6.5.0
    volumes:
      - name: cypress-cache
        path: /root/.cache/Cypress
    commands:
      - cypress install
      - yarn test:e2e:ci
    environment:
      DATO_API_TOKEN:
        from_secret: DATO_API_TOKEN
      GATSBY_SENTRY_DSN:
        from_secret: GATSBY_SENTRY_DSN

volumes:
  - name: cypress-cache
    host:
      path: /tmp/cypress-cache
