kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      restore: true
      cache_key: '{{ .Repo.Name }}-{{ checksum "yarn.lock" }}'
      archive_format: 'gzip'
      bucket: stiforr-drone-cache
      region: us-east-1
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - 'node_modules'
        - '.cache'
        - 'public'
        - '.lighthouseci'
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    volumes:
      - name: cache
        path: /tmp/cache

  - name: install
    image: node
    commands:
      - yarn install --frozen-lockfile
    when:
      branch:
        include:
          - master
          - develop
          - 'feature/*'
          - 'hotfix/*'
        exlude:
          - 'renovate/*'
    depends_on:
      - restore-cache-with-filesystem

  - name: build
    image: node
    commands:
      - yarn build
    when:
      branch:
        include:
          - master
          - develop
          - 'feature/*'
          - 'hotfix/*'
        exlude:
          - 'renovate/*'
    environment:
      DATO_API_TOKEN:
        from_secret: DATO_API_TOKEN
      GATSBY_SENTRY_DSN:
        from_secret: GATSBY_SENTRY_DSN
    depends_on:
      - install

  - name: lighthouse
    image: stiforr/node-chrome:v3
    pull: true
    commands:
      - su node
      - yarn lhci autorun
    when:
      branch:
        include:
          - master
          - develop
          - 'feature/*'
          - 'hotfix/*'
        exlude:
          - 'renovate/*'
    environment:
      LHCI_TOKEN:
        from_secret: LHCI_TOKEN
      LHCI_GITHUB_APP_TOKEN:
        from_secret: LHCI_GITHUB_APP_TOKEN
    depends_on:
      - install
      - build

  - name: rebuild-cache-with-filesystem
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      rebuild: true
      cache_key: '{{ .Repo.Name }}-{{ checksum "yarn.lock" }}'
      archive_format: 'gzip'
      bucket: stiforr-drone-cache
      region: us-east-1
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - 'node_modules'
        - '.cache'
        - 'public'
        - '.lighthouseci'
    volumes:
      - name: cache
        path: /tmp/cache
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    depends_on:
      - install
      - build

  # - name: tests
  #   image: cypress/included:6.5.0
  #   commands:
  #     - cypress install
  #     - yarn test:e2e:ci
  #   environment:
  #     DATO_API_TOKEN:
  #       from_secret: DATO_API_TOKEN
  #     GATSBY_SENTRY_DSN:
  #       from_secret: GATSBY_SENTRY_DSN
  #   depends_on:
  #     - install

  - name: deploy
    image: node
    commands:
      - yarn global add firebase-tools firebase-ci
      - firebase-ci deploy
    environment:
      FIREBASE_TOKEN:
        from_secret: FIREBASE_TOKEN
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
          - tag
    depends_on:
      - build

  - name: semantic-release
    image: node
    commands:
      - yarn semantic-release
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
          - tag
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    depends_on:
      - build
      - deploy

volumes:
  - name: cache
    host:
      path: /var/lib/cache
