kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: cypress/included:6.5.0
    commands:
      - yarn install --frozen-lockfile

  - name: build
    image: cypress/included:6.5.0
    commands:
      - yarn build
    environment:
      DATO_API_TOKEN:
        from_secret: DATO_API_TOKEN
      GATSBY_SENTRY_DSN:
        from_secret: GATSBY_SENTRY_DSN
    depends_on:
      - install

  # - name: tests
  #   image: cypress/included:6.5.0
  #   commands:
  #     - cypress install
  #     - yarn test:e2e:ci
  #   environment:
  #     DATO_API_TOKEN:
  #       from_secret: DATO_API_TOKEN
  #     GATSBY_SENTRY_DSN:
  #       from_secret: GATSBY_SENTRY_DSN
  #   depends_on:
  #     - install

  - name: deploy
    image: node
    commands:
      - yarn global add firebase-tools firebase-ci
      - firebase-ci deploy
    environment:
      FIREBASE_TOKEN:
        from_secret: FIREBASE_TOKEN
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
    depends_on:
      - build

  - name: semantic-release
    image: node
    commands:
      - yarn semantic-release
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    depends_on:
      - build
      - deploy
