language: node_js
node_js: 14

cache:
  yarn: true
  directories: ~/.cache

stages:
  - 'Build assets'
  - 'Lint and e2e tests'
  - 'Deploy and Release'

jobs:
  include:
    - stage: 'Build assets'
      script: yarn build

    - stage: 'Lint and e2e tests'

      script: yarn lint
      name: 'Lint'

      script: yarn test:e2e:ci
      name: 'E2E'

    - stage: 'Deploy and Release'
      if: NOT type IN (pull_request) AND branch = master
      script: yarn semantic-release
      name: 'Release'

      script: yarn deploy
      name: 'Deploy'