language: node_js
node_js: 14

jobs:
  include:
    - stage: 'Lint'
      cache: yarn
      script: yarn lint

    - stage: 'End to end tests'
      script: yarn test:e2e:ci

    - stage: 'Release'
      if: branch = master
      script: yarn semantic-release
