language: node_js
node_js: 14

cache:
  yarn: true
  directories: /home/travis/.cache

jobs:
  include:
    - stage: 'Lint'
      script: yarn lint

    - stage: 'End to end tests'
      script: yarn test:e2e:ci

    - stage: 'Release'
      if: branch = master
      script: yarn semantic-release
