name: Build project and run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
          npm run build
        env:
          DATO_API_TOKEN: ${{ secrets.DATO_API_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.4.3
          lhci autorun || echo "LHCI failed!"
        env:
          LCHI_TOKEN: ${{ secrets.LCHI_TOKEN }}